export const GET_CREDENTIAL_BEGIN = 'GET_CREDENTIAL_BEGIN'
export const GET_CREDENTIAL_SUCCESS = 'GET_CREDENTIAL_SUCCESS'
export const GET_CREDENTIAL_FAILURE = 'GET_CREDENTIAL_FAILURE'
export const FORCE_LOGOUT_SUCCESS = 'FORCE_LOGOUT_SUCCESS'
