export const GET_LIST_BEGIN = 'GET_LIST_BEGIN'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE'

export const REMOVE_LIST_BEGIN = 'REMOVE_LIST_BEGIN'
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS'
export const REMOVE_LIST_FAILURE = 'REMOVE_LIST_FAILURE'

export const CHANGE_STATUS_BEGIN = 'CHANGE_STATUS_BEGIN,'
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS,'
export const CHANGE_STATUS_FAILURE = 'CHANGE_STATUS_FAILURE'
